### ISSUE TITLE
Fix SCOP accessions to use traditional notation

### ISSUE THREAD

**Issue by MattBashton** [m-crown/ProCogGraph#5]
For the SCOP version of the data set it would be good to have the traditional Accession for domains so `c.2.1.` rather than `51735` _etc_. in the table below. See https://scop.berkeley.edu/downloads/parse/dir.des.scop.1.75.txt
specifically the 3rd column. 
![7db0c26f-aadf-488b-ba88-7426b0be7ddd](https://github.com/user-attachments/assets/e967837e-4b6d-4fc7-a2e5-ed4bab8fb3f9)

**Comment by m-crown** [comment]
fixed in latest commit (de567e04fc59dd627283c6e44d5605c97aceff25)
